version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
      - ~/drives/media:/media
    environment:
      - TZ=America/New_York
    restart: always
    network_mode: host
