- id: '1595170191275'
  alias: Turn on the the lights when I get home
  description: ''
  trigger:
  - entity_id: person.chris
    event: enter
    platform: zone
    zone: zone.home
  condition:
  - after: sunset
    before: sunrise
    condition: sun
  action:
  - brightness_pct: 100
    device_id: 51abd68633b84fb9b60f4707abdf3482
    domain: light
    entity_id: light.vestibule_light
    type: turn_on
  - brightness_pct: 100
    device_id: 9b515446c8bc4ea198c44beeb4d2a45f
    domain: light
    entity_id: light.vestibule_light_2
    type: turn_on
# Custom pi-Hole stuff
- alias: Disable Pi-Hole
  trigger:
    platform: state
    entity_id: input_select.pihole_time
  condition:
    - condition: template
      value_template: "{{ is_state('input_select.pihole_time', 'Select Time') == false}}"    
  action:
    service: shell_command.pihole_disable
- alias: Reset PiHole Disable Time
  trigger:
    - platform: state
      entity_id: script.enable_pihole
    - platform: state
      entity_id: sensor.pihole_status
      from: 'disabled'
      to: 'enabled'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.pihole_time
      option: Select Time

