# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

pi_hole:
  - host: "192.168.0.101"
    api_key: !secret pi_hole_api_key

# platform: command_line
#   - switches:
#     - pihole_switch:
#       - friendly_name: PiHole Switch
#         command_on: "curl -X GET 'http://192.168.0.101/admin/api.php?enable&auth='"
#         command_off: "curl -X GET 'http://192.168.0.101/admin/api.php?disable=60&auth='"
#         command_state: "curl -X GET 'http://192.168.0.101/admin/api.php?status'"
#         value_template: "{{ value_json.status == 'enabled' }}"

input_select:
  pihole_time:
    name: Disable Time (minutes)
    options:
      - Select Time
      - 1
      - 5
      - 10
      - 60
      - 180
    initial: Select Time

shell_command:
  pihole_enable: curl -X GET 'http://192.168.0.101/admin/api.php?enable&auth='
  pihole_disable: curl -X GET 'http://192.168.0.101/admin/api.php?disable={{ float(states.input_select.pihole_time.state)  * 60}}&auth='
  pihole_status: curl -X GET 'http://192.168.0.101/admin/api.php?status'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
