# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

pi_hole:
  - host: "192.168.0.101"
    api_key: !secret pi_hole_api_key

input_select:
  pihole_time:
    name: Disable Time (minutes)
    options:
      - Select Time
      - 1
      - 5
      - 10
      - 60
      - 180
    initial: Select Time

shell_command:
  pihole_enable: curl -X GET 'http://192.168.0.101/admin/api.php?enable&auth='
  pihole_disable: curl -X GET 'http://192.168.0.101/admin/api.php?disable={{ float(states.input_select.pihole_time.state)  * 60}}&auth='
  pihole_status: curl -X GET 'http://192.168.0.101/admin/api.php?status'

# spotify
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# security camera streams
camera:
  - platform: generic
    name: pisensor1_cam
    still_image_url: https://media.istockphoto.com/photos/niagara-falls-picture-id508345252?k=6&m=508345252&s=170667a&w=0&h=bfGaBsL8VfBTLqJxFPwm8cXGaZLsgL34Ga4JSrhTtN0=
    stream_source: rtsp://192.168.0.158:8554/streaming

camera:
  - platform: generic
    name: pisensor2_cam
    still_image_url: https://media.istockphoto.com/photos/niagara-falls-picture-id508345252?k=6&m=508345252&s=170667a&w=0&h=bfGaBsL8VfBTLqJxFPwm8cXGaZLsgL34Ga4JSrhTtN0=
    stream_source: rtsp://192.168.0.162:8554/streaming

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
